import {voiceProfiles} from './voice-profiles.js';

export const companions=Object.freeze([
  {id:'nova',name:'Nova',description:'Everyday companion',accent:'#f59abf',palette:{surface:'#1b1017',raised:'#2d1723',inset:'#100910',soft:'#f5dce5',muted:'#b7869b',hairline:'#f59abf2e',signal:'#ffbd8d',from:'#382032',to:'#160d15','workspace-from':'#42253a','workspace-to':'#170e17'},asset:'nova',voice:voiceProfiles.nova,presence:{IDLE:'Warmly attentive',LISTENING:'Listening closely',THINKING:'Turning it over',SPEAKING:'Sharing a thought',WORKING:'Staying with it'}},
  {id:'sterling',name:'Sterling',description:'Planning companion',accent:'#75a9e8',palette:{surface:'#0f1723',raised:'#17263a',inset:'#09111b',soft:'#dbe9fa',muted:'#8da9c9',hairline:'#75a9e82e',signal:'#aacbff',from:'#203451',to:'#0d1624','workspace-from':'#293e5c','workspace-to':'#0d1725'},asset:'sterling',voice:voiceProfiles.sterling,presence:{IDLE:'At your service',LISTENING:'Giving this care',THINKING:'Considering the details',SPEAKING:'Putting it plainly',WORKING:'Keeping watch'}},
  {id:'rivet',name:'Rivit',description:'Coding companion',accent:'#79d8ef',palette:{surface:'#0c1a20',raised:'#142c34',inset:'#071217',soft:'#d7f1f4',muted:'#83afb7',hairline:'#79d8ef2e',signal:'#9df0da',from:'#1d3c45',to:'#0b171c','workspace-from':'#244751','workspace-to':'#0c181d'},asset:'rivet',voice:voiceProfiles.rivet,presence:{IDLE:'Ready to build',LISTENING:'Tracking the signal',THINKING:'Finding the angle',SPEAKING:'Calling it straight',WORKING:'On the problem'}},
  {id:'luma',name:'Luma',description:'Design companion',accent:'#64dfff',palette:{surface:'#101525',raised:'#1b2541',inset:'#090d19',soft:'#e2e8ff',muted:'#9aa9d4',hairline:'#64dfff2e',signal:'#afa8ff',from:'#263455',to:'#101527','workspace-from':'#30405f','workspace-to':'#101527'},asset:'luma',voice:voiceProfiles.luma,presence:{IDLE:'Looking for an idea',LISTENING:'Taking it in',THINKING:'Exploring the shape',WORKING:'Making it take form',SPEAKING:'Following the thread'}},
]);

export const companionById=Object.freeze(Object.fromEntries(companions.map(companion=>[companion.id,companion])));
