// Install socket capture and runtime guards before widget-runtime.js creates the WebSocket.
import {installSocketBridge} from '../conversation/socket-bridge.js';
import {installRuntimeEventGuard} from '../conversation/runtime-events.js';
import {installDualSpeakerEqualizers} from '../avatar/dual-speaker-patch.js';
installSocketBridge(window);
installRuntimeEventGuard(window);
installDualSpeakerEqualizers();
await import('./widget-runtime.js');
import '../styles/design-tokens.css';
import '../styles/widget-cockpit.css';
import '../styles/widget-panels.css';
import '../styles/widget-polish.css';
import '../styles/full-polish.css';
import '../styles/widget-stack.css';
import '../conversation/chat-actions.css';
import '../conversation/coding-edits.css';
import '../avatar/presence-orchestrator.css';
import '../workspace/unified-workspace.css';
import '../workspace/companion-workspace.css';
import '../workspace/agent-task.css';
import '../workspace/system-cockpit.css';
import {mountWidgetPanels} from '../widget/panels.js';
import {mountSpecialistState} from '../widget/specialist-state.js';
import {mountAgentUxGuard} from '../widget/agent-ux-guard.js';
import {mountRivetTaskController} from '../widget/rivet-task-controller.js';
import {mountRivetWorkspace} from '../widget/rivet-workspace.js';
import {mountRivetTaskPresentation} from '../widget/rivet-task-presentation.js';
import {mountInteractionState} from '../widget/interaction-state.js';
import {mountReadinessUI} from '../conversation/readiness-ui.js';
import {installCaptureLifecycleGuards} from '../audio/lifecycle.js';
import {mountCanonicalChat} from '../conversation/chat-ui.js';
import {mountCodingEdits} from '../conversation/coding-edits.js';
import {mountLatencyUI} from '../conversation/latency-ui.js';
import {mountInteractionIntelligence} from '../conversation/interaction-intelligence.js';
import {mountIdlePresence} from '../avatar/idle-presence.js';
import {mountPresenceOrchestrator} from '../avatar/presence-orchestrator.js';
import {mountReadinessPresence} from '../avatar/readiness-presence.js';
import '../avatar/readiness-presence.css';
import {mountUnifiedWorkspace} from '../workspace/unified-workspace.js';
import {mountSystemCockpit} from '../workspace/system-cockpit.js';
mountSpecialistState(window,document);
mountWidgetPanels(document, window.desktop);
mountRivetTaskController(window,document,window.desktop);
mountAgentUxGuard(window,document);
mountRivetWorkspace(window,document);
mountRivetTaskPresentation(window,document);
mountReadinessUI(window,document);
mountInteractionState(window,document);
installCaptureLifecycleGuards(window,document);
mountCanonicalChat(window,document);
mountCodingEdits(window,document);
mountLatencyUI(window,document);
mountInteractionIntelligence(window,document);
mountIdlePresence(window,document);
mountPresenceOrchestrator(window,document);
mountReadinessPresence(window,document);
mountUnifiedWorkspace(window,document);
mountSystemCockpit(window,document);